### ISSUE TITLE
How to change configuration?

### ISSUE THREAD

**Issue by rinodung** [orditeck/c9ui#1]
As your suggestion how to change these configuration?

c9ui needs some basic information before you can start using it.
Setting     Example value   Required
Home user path  /home/c9ui  Yes
NodeJS full path    /usr/bin/nodejs     Yes
Cloud9 server.js full path  /home/c9ui/c9sdk/server.js  Yes
Default options     --listen 0.0.0.0 --auth test:test   No

**Comment by orditeck** [comment]
You can change theses configurations in the "settings" page:

![](http://i.imgur.com/zRgLADz.jpg)

Below the fields you'll find some useful informations that may help you to fill the settings.
