### ISSUE TITLE
Where can I set host and port?

### ISSUE THREAD

**Issue by StijnBousard** [orditeck/c9ui#10]
I am able to intall the c9ui, and when I issue the command:
`php artisan serve`
Then the server is started, as it outputs:
`Lumen development server started on http://localhost:8000/`
But I cannot access it.
I'm using a shared hosting, with the PHP built-in web server. Is there a possibility to change the host and port somewhere?

**Comment by orditeck** [comment]
Hi, `artisan` is from Lumen, which is the PHP microframework this little app has been made on. You can see the options available for this command by running `php artisan serve --help`

```
➜  c9ui git:(master) php artisan serve --help
Usage:
  serve [options]

Options:
      --host[=HOST]     The host address to serve the application on. [default: "localhost"]
      --port[=PORT]     The port to serve the application on. [default: 8000]
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Serve the application on the PHP development server
```

What your trying to achieve could be done using the following command: `php artisan serve --port=8001`

That answer the question `Is there a possibility to change the host and port somewhere?`.

However, you also said that you're trying to install this on a shared hosting. If you're using cPanel, for example, you could create a subdomain `c9ui.domain.com` and simply point its root document to the [`public`](https://github.com/orditeck/c9ui/tree/master/public) directory of this project. 

`php artisan serve` is to serve/execute the files using a web server and a PHP handler. It's for dev/test purpose. It shouldn't be used in production.

As you're on a shared hosting, you already have a web server and (usually) a PHP handler. Like Apache or nginx.

Please refer to the [readme](https://github.com/orditeck/c9ui/blob/master/readme.md), just after the `php artisan serve` command.
