### ISSUE TITLE
c9ui triggers Cloud9 installer, c9 command line doesn't...

### ISSUE THREAD

**Issue by StijnBousard** [orditeck/c9ui#11]
Hi Keven,

Thanks to your explanation, I was able to start the c9ui successfully. I now have a problem of a different kind:
C9 COMMAND LINE
If I start c9 from the ssh command line, it works fine: I start from ~/c9sdk and issue the following command:
~/.c9/node/bin/node server.js -p 1234 -a <user>:<password> --listen <ipaddress> -w ~/domains/<domain.suf>/public_html/<workspace>
and I am able to access the cloud9 environment without problems.

C9UI
My c9ui settings are as follows:
Settings
	Home user path: ~/.c9/node/bin
	NodeJS full path: ~/.c9/node/bin/node
	Cloud9 server.js full path: ~/c9sdk/server.js
	Default options: -a <user>:<password> --listen <ipaddress>
Workflows
	2	Name: <name>
		Path: ~/domains/<domain.suf>/public_html/<workspace>
		Options: -p 1234
Again, the cloud9 environment is accessible, however a Cloud9 Installer popup appears. If I click Next to install all components (Node.js, Pty.js, tmux, Nak), it fails on tmux (the popup also appears if I use the -k option).
   _checking for library containing setupterm... no
   configure: error: "curses not found"
   Compiling Tmux
   make: *** No targets specified and no makefile found.  Stop.
   make: *** No rule to make target `install'.  Stop.
   Installing Tmux
   Installed tmux does not appear to work:
   exiting with 100

   Failed Bash. Exit code 100

   One or more errors occured. Please try to resolve them and restart Cloud9 or contact support@c9.io._

I checked with ps -ef for the command line string, but even if I manually enter the slightly different one that is issued by c9ui, I don't get the popup...

Any ideas what's different and how I could correct it?

Thanks in advance!

**Comment by StijnBousard** [comment]
It's always good to write down your issues - it helps to find the solution...
The Chrome Developer tools showed me what was wrong.

WRONG:
Home user path: ~/.c9/node/bin
RIGHT:
Home user path: /home/<userid>

Your readme.md gives a good example, however I followed the misleading hint in the interface:
Home user path ($HOME) (e.g.: /usr/bin/nodejs)

So, the problem is solved and my c9 environments can now be launched without ssh interference and without c9 Installer popup! Many thanks for this great small web app!

**Comment by orditeck** [comment]
Happy to read that you found the solution 😃
