### ISSUE TITLE
I can't access the project in the browser

### ISSUE THREAD

**Issue by SamLucas** [orditeck/c9ui#13]
Hello, all right? I am trying to use your project, but I can't make it work. It even works but I can't access it in the browser. My goal is to put your project in a docker image for use in my college, if you have a project that is no longer supported could you recommend me another alternative?

**Comment by orditeck** [comment]
Hi, thanks for your interest in this project.

Please follow https://github.com/orditeck/c9ui#install-c9ui

The `php artisan serve` command should give you a web server running on http://localhost:8000.

Also, please read https://github.com/orditeck/c9ui#about.
