### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by EpicnessTwo** [orditeck/c9ui#3]
Hi,

Im getting this error. Is it fixable?

https://i.epickitty.uk/LE427Z

**Comment by orditeck** [comment]
Did you filled the `APP_KEY` in your `.env` file as instructed in the [install section](https://github.com/orditeck/c9ui#install-c9ui)?

> Now open your `.env` file and fill in the `APP_KEY` setting ([32 chars random string](http://randomkeygen.com/))

**Comment by EpicnessTwo** [comment]
Solved, They key was only 30 chars long. Silly me :p

**Comment by orditeck** [comment]
Great! :smile:
