### ISSUE TITLE
Missing Nginx support

### ISSUE THREAD

**Issue by melroy89** [orditeck/c9ui#4]
Hi,

I'm Nginx server instead of Apache. I'm missing the nginx example file. Because .htaccess files only works for apache servers.

Example of a Nginx server file:

``` nginx
server {
        listen 80;
        root /var/www/c9ui.yourdomain.com/public;

        index index.html index.htm index.php;

        charset utf-8;

        server_name c9ui.yourdomain.com;

        location / {   
                try_files $uri $uri/ /index.php?$query_string;     
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        location ~ \.php(?:$|/) {
           fastcgi_split_path_info ^(.+\.php)(/.+)$;
           include fastcgi_params;
           fastcgi_index index.php;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           fastcgi_param PATH_INFO $fastcgi_path_info;
           fastcgi_param modHeadersAvailable true;
           fastcgi_param HTTPS on;
           fastcgi_pass php-handler;
           fastcgi_intercept_errors on;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        location ~ /\.ht {
                deny all;
        }
}                                          
```

Hopefully you will add this to some documentation. Thanks!

Kind regards,
Melroy

**Comment by orditeck** [comment]
Cool, thanks! Would you mind creating a pull request adding the file for Nginx & maybe even renaming "Workflows" to "Workspaces" as you recommend [here](https://github.com/c9/core/issues/237#issuecomment-212979017)? 

Edit: I never used Nginx, [there is a sample file suggested here for lumen](https://gist.github.com/psgganesh/8d1790dd0c16ab5a4cde). Which one would you recommend?

**Comment by orditeck** [comment]
Closing this. Feel free to contribue & create a pull request for Nginx support.
