### ISSUE TITLE
Cloud9 doesn't start?

### ISSUE THREAD

**Issue by melroy89** [orditeck/c9ui#5]
Hi,

When I configured everything. Which seems all ok. And finally press the 'start' button, I get:

> Workflow started. PID #29279 

However, I can't find any process with the PID nor a process with nodejs what I should expect. I think something really goes wrong (maybe port I use, I really don't know..), because I can't debug it! I tried the `--debug` argument without success. I don't know where your c9ui is logging the errors?

Also the server error log doesn't say anything.

Kind regards,
Melroy van den Berg

**Comment by orditeck** [comment]
You should try to login via SSH using the same user your web process works on and then try starting server.js using the same command/arguments.

For example for me I'd connect over SSH as orditeck and then I'd run `node /home/orditeck/c9sdk/server.js`. Check if you get any error. If you do, correct them. If you don't, then make sure you have `nohup` installed as c9ui needs it.

Edit: See [here](https://github.com/orditeck/c9ui/blob/master/app/Http/Controllers/WorkflowController.php#L94) for complete command

**Comment by melroy89** [comment]
Ok I will check it, but I already have a valid cloud 9 running (without c9ui), so my server should be able to run c9. I hoped to have better logging / error messages when something goes wrong instead of saying: "workflow started". 

You should check on any non-zero return code of any command you execute. When this is the case, you know for sure there is a problem and you show it to the user..

**Comment by orditeck** [comment]
Do you have `nohup` installed? I sent you the link with full command, which starts with `/usr/bin/nohup` so make sure you have it there, or change this part of the code yourself.

I know the code should check for error while executing the command but I created the web app for fun, for personal use, and said to myself "why not put that on github? maybe it'll be useful to someone". Feel free to contribute & create pull requests 😄 

Maybe you could just try to change line 103 of `WorkflowController.php` to `return redirect('workflows')->with('status_success', "Workflow started. PID #{$pid} ($return)");` just so that you see the full return from `shell_exec($command)` for temporary debugging.

Edit: Just realized it won't probably return anything useful. Best way would be to use `php artisan serve`, the terminal will output the errors if you have any. For example, I replaced `/usr/bin/nohup` for `/usr/bin/nohupe` just to get an error, and the terminal gave me:

```
➜  c9ui git:(master) ✗ php artisan serve
Lumen development server started on http://localhost:8000/
sh: /usr/bin/nohupe: No such file or directory
```

**Comment by melroy89** [comment]
```
$ which nohup
/usr/bin/nohup
```

(Default installed under Debian jessie) So that is OK.

Running `php artisan serve` instead of Nginx, I indeed get some output. Saying:
`/usr/bin/nohup: redirecting stderr to stdout`
When I pressed the start button. That's it... Uhm not very helpfull?

When I press the stop button I get:
`sh: 1: kill: No such process`

**Comment by orditeck** [comment]
After starting the workspace _(workflow)_, what does `ps` gives you? I don't get the message you get from `nohup`

**Comment by melroy89** [comment]
Instead of this shell_exec maybe I should use `passthru`, I read on the internet? Or... `exec` in PHP. Example (piping stderr to stdout to $result via `2>&1`):

``` php
echo exec("node .. bla bla 2>&1", $result);
echo "<pre>" .  $result . "</pre>";
```

ps doesn't show the process, because the process doesn't get started (or only for just for a smallllll moment). I have more things running on this server.. but I ran `ps -ef` before, and `ps -ef` after I pressed the 'start' button.

I diff-ed them:

``` diff
$ diff before.log after.log 
127c127
< git       8614 20673  0 20:01 ?        00:00:33 unicorn worker[0] -D -E production -c /var/opt/gitlab/gitlab-rails/etc/unicorn.rb /opt/gitlab/embedded/service/gitlab-rails/config.ru                           
---
> git       8614 20673  0 20:01 ?        00:00:34 unicorn worker[0] -D -E production -c /var/opt/gitlab/gitlab-rails/etc/unicorn.rb /opt/gitlab/embedded/service/gitlab-rails/config.ru                           
179d178
< root     31350   616  0 22:34 ?        00:00:00 sleep 30
185,186c184,186
< git      31402 20657  0 22:34 ?        00:00:00 sleep 1
< melroy   31403 23996  0 22:34 pts/1    00:00:00 ps -ef
---
> root     31426   616  0 22:34 ?        00:00:00 sleep 30
> git      31466 20657  0 22:34 ?        00:00:00 sleep 1
> melroy   31497 23996  0 22:35 pts/1    00:00:00 ps -ef
190c190
< gitlab-+ 31841 20618  0 15:28 ?        00:00:06 postgres: gitlab gitlabhq_production [local] idle 
---
> gitlab-+ 31841 20618  0 15:28 ?        00:00:06 postgres: gitlab gitlabhq_production [local] idle      
```

**Comment by melroy89** [comment]
Ps.
haha You write everything to /dev/null ><!! That means by default you dump all output to the dustbin.
WorkflowController.php:94:

``` php
$command = "/usr/bin/nohup {$settings->nodejs_path} {$settings->c9_path} -w {$workflow->path} {$workflow->args} {$settings->default_args} > /dev/null
```

**Comment by melroy89** [comment]
I continue tomorrow.. But I made some changes in the code... See:

``` php
$command = "/usr/bin/nohup {$settings->nodejs_path} {$settings->c9_path} -w {$workflow->path} {$workflow->args} {$settings->default_args}";
putenv("HOME={$settings->home_path}");

//$workflow->save();

$output1 = exec($command . " 2>&1", $result, $return);
var_dump($result);
return redirect('workflows')->with('status_success', "Workflow started. Command: " . $command . " - Return: " . $return . " - Output 1: " . $output1);

```

Giving me now the output:

```
Command: /usr/bin/nohup /usr/local/bin/node /var/www/c9.melroy.org/html/server.js -w /media/data/cloud9_workplace/test --debug - Return: 1 - Output 1: at process._tickCallback (node.js:369:17) 
```

**Comment by orditeck** [comment]
Seems like you're having an issue with your c9 install. 

Try to run `/usr/local/bin/node /var/www/c9.melroy.org/html/server.js -w /media/data/cloud9_workplace/test --debug`. I know you said that c9 was working but are you 100% sure you ran the install script for c9? Installation steps in your case would be:

```
cd /var/www/c9.melroy.org/html/
scripts/install-sdk.sh
```

Just want to make sure. If the command above is working in your terminal but not via `exec` or similar PHP function, maybe it's a permission issue.

**Comment by melroy89** [comment]
Yep tada.. Exactly what I though: address in use:

```
$ /usr/local/bin/node /var/www/c9.melroy.org/html/server.js -w /media/data/cloud9_workplace/test --debug                                                                             
Starting standalone                                                                                                                                                                                        
events.js:141                                                                                                                                                                                              
      throw er; // Unhandled 'error' event                                                                                                                                                                 
      ^                                                                                                                                                                                                    

Error: listen EADDRINUSE 127.0.0.1:8181                                                                                                                                                                    
    at Object.exports._errnoException (util.js:856:11)                                                                                                                                                     
    at exports._exceptionWithHostPort (util.js:879:20)                                                                                                                                                     
    at Server._listen2 (net.js:1234:14)                                                                                                                                                                    
    at listen (net.js:1270:10)                                                                                                                                                                             
    at net.js:1379:9                                                                                                                                                                                       
    at doNTCallback3 (node.js:463:9)                                                                                                                                                                       
    at process._tickCallback (node.js:369:17)                                                                                                                                                              
```

Meaning you are currently saying "Workflow started", but in reality the return value of the command is really returning a non-zero value, and something really goes wrong. Try to change your code by using 
exec() instead, and check the $return. Too bad $result is empty in my case ><? I don't know why.

Something like:

``` php
$command = "...";
$output = exec($command . " 2>&1", $result, $return);
# Non-zero?
if($return != 0) return redirect('workflows')->with('status_error', "Error while starting the server ($return).");
```

Hopefully this gives a better user-feedback. I try to find out why I didn't get this stacktrace above within PHP. (I only could print the last line: `at process._tickCallback (node.js:369:17)`, which is not that usefull xD)

**Comment by orditeck** [comment]
You can't have two workspaces running at the same time using c9ui, it is written that way. It can be changed of course. You shouldn't have any process using the same port you want to use. In fact the main point of c9ui is to use the same URL for c9 for multiples projects.

On Fri, Apr 22, 2016 at 7:46 AM, Melroy van den Berg < notifications@github.com [notifications@github.com] > wrote:
Yep tada.. Exactly what I though: address in use:

$ /usr/local/bin/node /var/www/c9.melroy.org/html/server.js -w /media/data/cloud9_workplace/test --debug                                                                             
Starting standalone                                                                                                                                                                                        
events.js:141                                                                                                                                                                                              
      throw er; // Unhandled 'error' event                                                                                                                                                                 
      ^                                                                                                                                                                                                    

Error: listen EADDRINUSE 127.0.0.1:8181                                                                                                                                                                    
    at Object.exports._errnoException (util.js:856:11)                                                                                                                                                     
    at exports._exceptionWithHostPort (util.js:879:20)                                                                                                                                                     
    at Server._listen2 (net.js:1234:14)                                                                                                                                                                    
    at listen (net.js:1270:10)                                                                                                                                                                             
    at net.js:1379:9                                                                                                                                                                                       
    at doNTCallback3 (node.js:463:9)                                                                                                                                                                       
    at process._tickCallback (node.js:369:17)                                                                                                                                                              


Meaning you are currently saying "Workflow started", but in reality the return value of the command is really returning a non-zero value, and something really goes wrong. Try to change your code by using
exec() instead, and check the $return. Too bad $result is empty in my case ><? I don't know why.

Something like:

$command="...";$output=exec($command." 2>&1", $result, $return);# Non-zero?if($return!=0) return redirect('workflows')->with('status_error', "Error while starting the server ($return).");

Hopefully this gives a better user-feedback. I try to find out why I didn't get this stacktrace above within PHP.

**Comment by orditeck** [comment]
You can't have two workspaces running at the same time using c9ui, [it's written that way](https://github.com/orditeck/c9ui/blob/master/app/Http/Controllers/WorkflowController.php#L82). You can only have one PID running. It can be changed of course, and it should. It'd be a great addition. It should check for port collision (so maybe require to specify a port when creating/updating a workspace)

And of course you shouldn't have any process using the same port you want to use. 

You can specify the port you want c9 to use with `--port 8282`.

I agree that there should be more check when the process starts.

**Comment by melroy89** [comment]
Yep I knew that this was probably the root case. check my first comment, saying:

> maybe port I use, I really don't know..

My goals was to fix your code in order to log an error instead of saying: `Workflow successfully started`. While in reality things go wrong. That is why I'm pushing to change the code in such a way that the $return really contains the command exit code.

**Comment by orditeck** [comment]
I'm glad that you found the issue. It'd be great if you could make it better & create a pull request. I'll close this issue. Thanks!

**Comment by melroy89** [comment]
Just one thing. The result was an array, so it should be:

``` php
$result = array();
exec($command . " 2>&1", $result, $return);
$result = implode("\n ", $result);
if($return != 0) return redirect('workflows')->with('status_error', "Error while starting the server ($return). Output: " . $result);
```

Then I get the nice full traceback, with all the info the end-user need. Too bad know you don't know the PID.
