### ISSUE TITLE
Basic Auth help

### ISSUE THREAD

**Issue by svinqvmraka** [orditeck/c9ui#6]
Ok, this may sound pretty dumb and it's not really an issue with your app(which is great btw, thanks for that!):

I can't for the love of me figure out how to make a working apache vhost with basic authentication for the lumen app. I have everything running on a VPS, with no domain(I'm absolutely fine with it being on http://_IP_:8000/) and the only thing I need is to setup basic authentication, so it's not directly exposed to the world. I've been trying to get a vhost working for the app for a while and I can't seem to get it to work properly. Is that even possible with no domain and can you share how you did it?

**Comment by orditeck** [comment]
You're referring to port 8000 so I guess you're using `php artisan serve` as web server?

If so, to keep it simple, I'd create a middleware in Lumen. Here are the steps:

Create the file `HttpBasicAuth.php` in `app/Http/Middleware/`:

```php
<?php

namespace App\Http\Middleware;

use Closure;

class HttpBasicAuth
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if($request->getUser() != 'USERNAME_HERE' && $request->getPassword() != 'PASSWORD_HERE') {
            return response('Unauthorized', 401, array('WWW-Authenticate' => 'Basic'));
        }

        return $next($request);
    }

}
```

In `bootstrap/app.php`, edit and replace
```php
// $app->routeMiddleware([
// ]);
```

to
```php
$app->routeMiddleware([
    App\Http\Middleware\HttpBasicAuth::class
]);
```

Didn't try it but should work!

If it gives you an error about a `HttpBasicAuth Class not found`, do a `composer dump-autoload` in your terminal.

**Comment by svinqvmraka** [comment]
Awesome, thanks for that, definitely pointed me in the right direction.
It doesnt execute for some reason if it's in `$app->routeMiddleware()`, but it seems to work fine if I register the middleware thing in `$app->middleware()`, along with the other already existing middlewares. Not sure what the reason is, but I'll definitely look more into it tommorow. Sorry if I'm not making much sense, this laravel/lumen thing is very new to me.
Thanks for the help!

**Comment by orditeck** [comment]
Glad it's working 😄
