### ISSUE TITLE
Heya trying to get this installed

### ISSUE THREAD

**Issue by Jafesu** [orditeck/c9ui#7]
Hey There,

I know this is a bit old but hoped you may be willing to still help me out,

when i run `php artisan migrate`

it returns the following error

`PHP Warning:  require_once(/var/www/html/c9ui/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/c9ui/bootstrap/app.php on line 3
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/c9ui/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/c9ui/bootstrap/app.php on line 3
`

**Comment by Jafesu** [comment]
So i did find that the issue is composer install is failing... i get the following messege


`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/lumen-framework v5.1.0 requires illuminate/encryption 5.1.* -> satisfiable by illuminate/encryption[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - laravel/lumen-framework v5.1.1 requires illuminate/encryption 5.1.* -> satisfiable by illuminate/encryption[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - laravel/lumen-framework v5.1.2 requires illuminate/encryption 5.1.* -> satisfiable by illuminate/encryption[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - laravel/lumen-framework v5.1.3 requires illuminate/encryption 5.1.* -> satisfiable by illuminate/encryption[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - laravel/lumen-framework v5.1.4 requires illuminate/encryption 5.1.* -> satisfiable by illuminate/encryption[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - laravel/lumen-framework v5.1.5 requires illuminate/encryption 5.1.* -> satisfiable by illuminate/encryption[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - laravel/lumen-framework v5.1.6 requires illuminate/encryption 5.1.* -> satisfiable by illuminate/encryption[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - laravel/lumen-framework v5.1.7 requires illuminate/encryption 5.1.* -> satisfiable by illuminate/encryption[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - illuminate/encryption v5.1.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.41 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.30 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.25 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.20 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.16 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.13 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/encryption v5.1.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - Installation request for laravel/lumen-framework 5.1.* -> satisfiable by laravel/lumen-framework[v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7].
`

**Comment by Jafesu** [comment]
AAAAAAAAAND i found it thanks anyway :D

**Comment by orditeck** [comment]
Glad you found out :)
