### ISSUE TITLE
Access externally

### ISSUE THREAD

**Issue by Jafesu** [orditeck/c9ui#8]
Hey there, so i have this issue, 

I am trying to access my c9ui instance externally and it is not connecting, is there a setting somewhere i need to change to make it run on 0.0.0.0 instead of localhost?

I am running this in an instance of ubuntu server so i have no UI so i cannot connect to localhost:8000 
I have set up port forwarding, my firewall is not blocking it, ETC.

i just cannot get it to connect.

thanks

**Comment by orditeck** [comment]
0.0.0.0 is external (meaning it'll listen to any ip).

**Comment by Jafesu** [comment]
Right, how do i set it to listen on 0.0.0.0 instead of localhost

**Comment by Jafesu** [comment]
after digging for a while i finally found it, now i am getting 

`No supported encrypter found. The cipher and / or key length are invalid`

**Comment by orditeck** [comment]
Yes, [as mentioned in the `readme`](https://github.com/orditeck/c9ui/blob/master/readme.md), you have to put a [32-char key in your `.env` file](https://github.com/orditeck/c9ui/blob/master/.env.example#L3). You can get a [generated one here](https://randomkeygen.com/)
